stages:
  - test

.composer_branch:
  stage: test
  script:
    - composer install
    - composer update
    - composer normalize
    - composer validate --strict
    - vendor/bin/grumphp run
    - composer test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

composer_branch_8.3:
  extends: .composer_branch
  image: kanti/buildy:8.3

composer_branch_8.4:
  extends: .composer_branch
  image: kanti/buildy:8.4

.composer_mr:
  stage: test
  script:
    - composer install
    - composer update
    - composer normalize
    - composer validate --strict
    - vendor/bin/grumphp run
    - composer test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

composer_mr_8.3:
  extends: .composer_mr
  image: kanti/buildy:8.3

composer_mr_8.4:
  extends: .composer_mr
  image: kanti/buildy:8.4
