pipelines:
  branches:
    "**":
      - step:
          name: Test 8.3 Branches
          image: kanti/buildy:8.3
          script:
            - composer install --no-interaction --no-progress --no-suggest --verbose --ignore-platform-reqs
            - composer update
            - composer normalize
            - composer validate --strict
            - vendor/bin/grumphp run
            - composer test
      - step:
          name: Test 8.4 Branches
          image: kanti/buildy:8.4
          script:
            - composer install --no-interaction --no-progress --no-suggest --verbose --ignore-platform-reqs
            - composer update
            - composer normalize
            - composer validate --strict
            - vendor/bin/grumphp run
            - composer test

  pull-requests:
    "**":
      - step:
          name: Test 8.3 PR
          image: kanti/buildy:8.3
          script:
            - composer install --no-interaction --no-progress --no-suggest --verbose --ignore-platform-reqs
            - composer update
            - composer normalize
            - composer validate --strict
            - vendor/bin/grumphp run
            - composer test
      - step:
          name: Test 8.4 PR
          image: kanti/buildy:8.4
          script:
            - composer install --no-interaction --no-progress --no-suggest --verbose --ignore-platform-reqs
            - composer update
            - composer normalize
            - composer validate --strict
            - vendor/bin/grumphp run
            - composer test
