services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AUS\AusSentryCronmonitor\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  AUS\AusSentryCronmonitor\Command\GenerateCronMonitorForAllTasksCommand:
    tags:
      - name: 'console.command'
        command: 'generateCronMonitor'
        description: ''
        hidden: false
